### ISSUE TITLE
Demo F2 crashes on Linux

### ISSUE THREAD

**Issue by dag7dev** [merumerutho/LOVJ#6]
## Steps
Environment: Pop OS! - Love2D Version: LOVE 11.3 (Mysterious Mysteries)

1. Run LOVJ

2. Press F2

3. Segmentation fault `Aborted (core dump created)`

**Comment by merumerutho** [comment]
Would you be able to run using at least 11.4? LOVJ has been developed using that version. Regardless, I will try to replicate on some Linux environment when I can.

**Comment by dag7dev** [comment]
Thanks, it was simpler than ever!
