### ISSUE TITLE
Add controls and description section in README

### ISSUE THREAD

**Issue by dag7dev** [merumerutho/LOVJ#8]
It would be nice to understand how to play with LOVJ without messing too much with code.

Here's an example of what could be that section.

## Controls
Here's an non-exhaustive list of controls:
- ESC: open DEBUG console
- F1...F12: change patch (see cfg/cfg_patches.lua to change demos)
- Win + Return: set fullscreen window
- G + Up/Down: regulate blur effect
- ...

**Comment by merumerutho** [comment]
A documentation is certainly due but I don't think all possible commands shall be entirely covered in the README. 
General controls can be certainly covered.
Considering the flexible and modular nature of LOVJ, demo and shader related commands can be covered directly inside their lua files.
